on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile Typst documents
        # You may pin to the exact commit or the version.
        # uses: Jarivanbakel/typst-action@6962851be1a1a5b9f953723e17bc69bf4b6ccee8
        uses: Jarivanbakel/typst-action@v3
        with:
          # Define the input files that need to be compiled to Typst documents
          input_files: main.typ
          # The working directory where all the typst files are located
          #working_directory: # optional
          # Defines the token to use to execute the git API requests with, uses `env.GITHUB_TOKEN` by default
          #token: # optional, default is ${{ github.token }}
